version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: info_distiller_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: infodistiller
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d infodistiller"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    build: ./gateway
    container_name: info_distiller_gateway
    ports:
      - "8082:8082"
    depends_on:
      db:
        condition: service_healthy

  agent-service:
    build: ./agent-service
    container_name: info_distiller_agent_service
    ports:
      - "8000:8000"
    # --- ADD THE FOLLOWING SECTIONS ---
    volumes:
      # This mounts our local secrets folder into the container at /app/secrets
      - ./secrets:/app/secrets
    environment:
      # This tells the Google SDK where to find the credentials inside the container
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/gcp-credentials.json
    # --- END OF ADDED SECTIONS ---
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: info_distiller_frontend
    ports:
      - "3000:3000"
    depends_on:
      - gateway

volumes:
  postgres_data: