package com.infodistiller.gateway.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Column;

// @Entity tells Spring Data JPA that this class is a representation of a database table.
@Table(name = "interests") // This maps the class to the "interests" table specifically.
@Entity
public class Interest {

    @Id // Marks this field as the primary key.
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Configures the ID to be auto-generated by the database.
    private Integer id;

    @Column(name = "user_id") // Maps this field to the "user_id" column.
    private Integer userId;

    private String name;

    @Column(name = "query_template")
    private String queryTemplate;

    public Integer getId() { return id; }
    public void setId(Integer id) { this.id = id; }
    public Integer getUserId() { return userId; }
    public void setUserId(Integer userId) { this.userId = userId; }
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    public String getQueryTemplate() { return queryTemplate; }
    public void setQueryTemplate(String queryTemplate) { this.queryTemplate = queryTemplate; }
}